// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9dD0MZSRgnFqgGeZYbt5ESvaPuAHmhE',
    appId: '1:291840111308:web:6c18206e457d537f4b4869',
    messagingSenderId: '291840111308',
    projectId: 'boilerplateapp-91533',
    authDomain: 'boilerplateapp-91533.firebaseapp.com',
    storageBucket: 'boilerplateapp-91533.appspot.com',
    measurementId: 'G-0YVM0SD953',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPoHE-Go9CM_xEnlWJMXKQ3qHLw69wK-k',
    appId: '1:291840111308:android:98630ea0ad1c5e284b4869',
    messagingSenderId: '291840111308',
    projectId: 'boilerplateapp-91533',
    storageBucket: 'boilerplateapp-91533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlDITkR5bNdVZ3uCfB0-I_bFZv0m9P57g',
    appId: '1:291840111308:ios:725fc4482c87f3be4b4869',
    messagingSenderId: '291840111308',
    projectId: 'boilerplateapp-91533',
    storageBucket: 'boilerplateapp-91533.appspot.com',
    iosClientId: '291840111308-epjupo3aut2u40n5gro6sjs6fsksq3ap.apps.googleusercontent.com',
    iosBundleId: 'com.kallso.boilerplateapp',
  );
}
