// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnfDgB4zCfV-lmDnotJZtcuRPEHa49q1M',
    appId: '1:882304476186:web:cfa45f306fa3e8f6cb5da3',
    messagingSenderId: '882304476186',
    projectId: 'iot-project-bcf43',
    authDomain: 'iot-project-bcf43.firebaseapp.com',
    storageBucket: 'iot-project-bcf43.appspot.com',
    measurementId: 'G-XRPV13TR4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFRPjKeQqtU9tcHaysr2vDuZWKGD5lqU',
    appId: '1:882304476186:android:ff1883f1b7a53eb6cb5da3',
    messagingSenderId: '882304476186',
    projectId: 'iot-project-bcf43',
    storageBucket: 'iot-project-bcf43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7P93rFrQGq9dAVmR30gECms9KlvXDY5k',
    appId: '1:882304476186:ios:72b5f18eedebfea4cb5da3',
    messagingSenderId: '882304476186',
    projectId: 'iot-project-bcf43',
    storageBucket: 'iot-project-bcf43.appspot.com',
    androidClientId: '882304476186-mkdnu7131krr36v0796b76lkmnf8cfk8.apps.googleusercontent.com',
    iosClientId: '882304476186-jds43e66djpj0r6j2dq2nua2mctcvs3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.boilerplateApp',
  );
}
